### ISSUE TITLE
Shield Tracker

### ISSUE THREAD

**Issue by redbluee** [redbluee/BattleBot#6]
add temporary health pool to characters, which comes first in place when taking dmg till its depleted

**Comment by JonnyEisenfaust** [comment]
Characters already have a temp hp attribute. Taking dmg to temp hp works as intended. Only issue here is, that the damage you recieve on your temp hp isnt properly displayed.

**Comment by astrionn** [comment]
Closing this as a duplicate of #9. The temporary HP/shield damage display will be handled as part of the monitoring system implementation.
